### ISSUE TITLE
GET endpoint for partitioning's main flow

### ISSUE THREAD

**Issue by salamonpavel** [AbsaOSS/atum-service#269] opened 2024-09-12 08:15 UTC
Implement the below endpoint
GET /flows/{flowId}/checkpoints?name= returns sequence Checkpoints PAGINATION

**Comment by lsulak** [comment] 2024-09-16 09:24
Closing, a duplicate of https://github.com/AbsaOSS/atum-service/issues/233, will pick up https://github.com/AbsaOSS/atum-service/issues/234 instead of this one

**Closed by lsulak** 2024-09-16 09:24 UTC
Labels: enhancement
