### ISSUE TITLE
Implement getFlowCheckpoints related functionality in Atum Server

### ISSUE THREAD

**Issue by salamonpavel** [AbsaOSS/atum-service#223] opened 2024-07-31 11:14 UTC
Implement getFlowCheckpoints related functionality in Atum Server.

```scala
// in FlowControllerImpl
override def getFlowCheckpointsV2(
    flowId: Long,
    checkpointName: Option[String],
    limit: Option[Int],
    offset: Option[Long]
  ): IO[ErrorResponse, PaginatedResponse[CheckpointDTO]]

// in FlowServiceImpl
override def getFlowCheckpoints(
    flowId: Long,
    checkpointName: Option[String],
    limit: Option[Int],
    offset: Option[Long]
  ): IO[ServiceError, PaginatedResult[CheckpointDTO]]

// in FlowRepositoryImpl
override def getFlowCheckpoints(
    flowId: Long,
    checkpointName: Option[String],
    limit: Option[Int],
    offset: Option[Long]
  ): IO[DatabaseError, PaginatedResult[CheckpointFromDB]]
```

Also the SQL code and Fa-db class need to be re-implemented.

**Comment by benedeki** [comment] 2024-09-17 09:23
Duplicate of #233

**Closed by benedeki** 2024-09-17 09:23 UTC
Labels: enhancement
