### ISSUE TITLE
Implement functionality for getPartitioningsEndpointV2

### ISSUE THREAD

**Issue by salamonpavel** [AbsaOSS/atum-service#225] opened 2024-07-31 12:17 UTC
Implement missing functionality for the endpoint below on all levels - Controller, Service, Repository, Fa-DB, SQL.
```scala
case class PartitioningWithIdDTO (
  id: Long,
  partitioning: PartitioningDTO,
  parentPartitioning: Option[PartitioningDTO],
  author: String
)

object PartitioningWithIdDTO {
  implicit val encoderPartitioningWithIdDTO: Encoder[PartitioningWithIdDTO] = deriveEncoder
  implicit val decoderPartitioningWithIdDTO: Decoder[PartitioningWithIdDTO] = deriveDecoder
}

// Endpoints
protected val getPartitioningsEndpointV2: PublicEndpoint[
    (Option[String], Option[String], Option[String]),
    ErrorResponse,
    PaginatedResponse[PartitioningWithIdDTO],
    Any
  ] = {
    apiV2.get
      .in(V2Paths.Partitionings)
      .in(query[Option[String]]("partitions"))
      .in(query[Option[String]]("limit"))
      .in(query[Option[String]]("offset"))
      .out(statusCode(StatusCode.Ok))
      .out(jsonBody[PaginatedResponse[PartitioningWithIdDTO]])
  }

// Routes
createServerEndpoint[
        (Option[String], Option[String], Option[String]),
        ErrorResponse,
        PaginatedResponse[PartitioningWithIdDTO]
      ](
        getPartitioningsEndpointV2,
        { case (partitions: Option[String], limit: Option[String], offset: Option[String]) =>
          PartitioningController.getPartitioningsV2(partitions, limit, offset)
        }
      )

// Controller
override def getPartitioningsV2(
    partitions: Option[String],
    limit: Option[String],
    offset: Option[String]
  ): IO[ErrorResponse, PaginatedResponse[PartitioningWithIdDTO]]

// Service
override def getPartitionings(
    partitions: Option[String],
    limit: Option[String],
    offset: Option[String]
  ): IO[ServiceError, PaginatedResult[PartitioningWithIdDTO]]

// Repository
def getPartitionings(
    partitions: Option[String],
    limit: Option[String],
    offset: Option[String]
  ): IO[DatabaseError, PaginatedResult[PartitioningWithIdDTO]]
```

**Comment by benedeki** [comment] 2024-09-17 09:22
Duplicate of #268

**Closed by benedeki** 2024-09-17 09:22 UTC
Labels: enhancement
